# Generated by Django 5.2.4 on 2025-08-11 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default='entrada', max_length=10),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='reason',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste')], default='ajuste', max_length=10),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
